### ISSUE TITLE
Adding repositories to source.list.d instead of source.list

### ISSUE THREAD

**Issue by lofidevops** [seatgeek/bash-aptfile#4]
**User story:** I am a system administrator. I would like to add a list of repositories to a single file in `/etc/apt/sources.list.d/` rather than append to `/etc/apt/sources.list`, so that I see and manage groups of repositories.

For example, if I were [installing FusionDirectory](https://www.fusiondirectory.org/debian/), I would want to create `/etc/apt/sources.list.d/fusiondirectory.list` with the following content:

```
deb http://repos.fusiondirectory.org/fusiondirectory-current/debian-jessie jessie main
deb-src http://repos.fusiondirectory.org/fusiondirectory-current/debian-jessie jessie main
deb http://repos.fusiondirectory.org/fusiondirectory-extra/debian-jessie jessie main
deb-src http://repos.fusiondirectory.org/fusiondirectory-extra/debian-jessie jessie main
```

**Suggested implementation:**

A new primitive called *repository_file* that works as follows:

```
repository_file "fusiondirectory.list" "deb http://repos.fusiondirectory.org/fusiondirectory-current/debian-jessie jessie main"
repository_file "fusiondirectory.list" "deb-src http://repos.fusiondirectory.org/fusiondirectory-current/debian-jessie jessie main"
...
```

**Comment by josegonzalez** [comment]
Seems legit, I would take a PR for this :)

How do we ensure that repository doesn't exist in *another* file?
